services:
  master:
    build:
      context: .
    ports:
      - 3306:3306
      - 22:22
      - 8080:8080
      - 8081:8081
    container_name: master
    depends_on:
      - child
      - leaf1
      - leaf2
  child:
    image: singlestoretraining/ubuntu_child:latest
    container_name: child
  leaf1:
    image: singlestoretraining/ubuntu_leaf1:latest
    container_name: leaf1
  leaf2:
    image: singlestoretraining/ubuntu_leaf2:latest
    container_name: leaf2
  setup:
    env_file: .env
    build:
      context: .
      dockerfile: setup.Dockerfile
      args:
        LICENSE: $LICENSE
        PASSWORD: $PASSWORD
    environment:
      MASTER_HOST: master
      CHILD_HOST: child
      LEAF1_HOST: leaf1
      LEAF2_HOST: leaf2
    container_name: setup
    depends_on:
      - master
networks:
  default:
    name: edu
